"""Offline ICD-10 catalog used by the medical document builder.

The historical public module name is still ``icd10_f_data`` for backward
compatibility, but the catalog is no longer restricted to class V / F00-F99.
It contains:
- all ICD-10 chapter/section rows (A00-Z99 and U00-U99);
- ICD-10 block rows across the full classification;
- the existing detailed F00-F99 rows used by earlier psychiatric workflows;
- a compact set of common cross-specialty rubrics for surgery/therapy/etc.

The chapter rows are localized for every language supported by the program.
Detailed rows keep the trusted Russian wording and are searchable in Russian;
the UI falls back safely where a bundled translation is not present.
"""

from __future__ import annotations

import re

from medical_language_catalog import SUPPORTED_LANGUAGE_IDS, normalize_language_id
from icd10_models import ICD10Diagnosis


_SECTION_KIND = "section"
_BLOCK_KIND = "block"
_RUBRIC_KIND = "diagnosis"
_LANGS = tuple(lang for lang in SUPPORTED_LANGUAGE_IDS if lang != "auto")


def _complete_titles(ru: str, en: str, **localized: str) -> dict[str, str]:
    titles = {"ru": ru, "en": en}
    titles.update({key: value for key, value in localized.items() if value})
    for lang in _LANGS:
        titles.setdefault(lang, titles.get("ru") or titles.get("en") or ru)
    return titles


def _row(code: str, ru: str, en: str = "", *, kind: str = _RUBRIC_KIND, **localized: str) -> ICD10Diagnosis:
    titles = _complete_titles(ru, en or ru, **localized)
    return ICD10Diagnosis(code=code, title=titles["ru"], titles=titles, kind=kind)


_SECTION_ROWS: list[ICD10Diagnosis] = [
    _row(
        "A00-B99",
        "Класс I. Некоторые инфекционные и паразитарные болезни",
        "Chapter I. Certain infectious and parasitic diseases",
        kind=_SECTION_KIND,
        uk="Клас I. Деякі інфекційні та паразитарні хвороби",
        be="Клас I. Некаторыя інфекцыйныя і паразітарныя хваробы",
        kk="I класс. Кейбір инфекциялық және паразиттік аурулар",
        uz="I sinf. Ayrim yuqumli va parazitar kasalliklar",
        az="I sinif. Bəzi infeksion və parazitar xəstəliklər",
        hy="I դաս. Որոշ վարակիչ և մակաբուծային հիվանդություններ",
        ka="I კლასი. ზოგიერთი ინფექციური და პარაზიტული დაავადება",
        tg="Синфи I. Баъзе бемориҳои сироятӣ ва паразитӣ",
        tk="I synp. Käbir ýokanç we parazit keseller",
    ),
    _row(
        "C00-D48",
        "Класс II. Новообразования",
        "Chapter II. Neoplasms",
        kind=_SECTION_KIND,
        uk="Клас II. Новоутворення",
        be="Клас II. Наватворы",
        kk="II класс. Жаңа түзілімдер",
        uz="II sinf. O‘smalar",
        az="II sinif. Yeni törəmələr",
        hy="II դաս. Նորագոյացություններ",
        ka="II კლასი. ახალწარმონაქმნები",
        tg="Синфи II. Навомосҳо",
        tk="II synp. Täze döremeler",
    ),
    _row(
        "D50-D89",
        "Класс III. Болезни крови, кроветворных органов и отдельные нарушения иммунного механизма",
        "Chapter III. Diseases of the blood and blood-forming organs and certain immune disorders",
        kind=_SECTION_KIND,
        uk="Клас III. Хвороби крові, кровотворних органів та окремі порушення імунного механізму",
        be="Клас III. Хваробы крыві, крывятворных органаў і асобныя парушэнні імуннага механізму",
        kk="III класс. Қан, қан түзуші ағзалар аурулары және иммундық механизмнің жекелеген бұзылыстары",
        uz="III sinf. Qon, qon yaratish a’zolari kasalliklari va ayrim immun buzilishlar",
        az="III sinif. Qan və qanyaradıcı orqan xəstəlikləri və immun mexanizmin bəzi pozğunluqları",
        hy="III դաս. Արյան, արյունաստեղծ օրգանների հիվանդություններ և իմունային մեխանիզմի առանձին խանգարումներ",
        ka="III კლასი. სისხლის, სისხლმბადი ორგანოების დაავადებები და იმუნური მექანիզմის ზოგიერთი დარღვევა",
        tg="Синфи III. Бемориҳои хун, узвҳои хунофар ва баъзе ихтилолҳои масуният",
        tk="III synp. Gan, gan dörediji agzalar keselleri we immun mehanizminiň käbir bozulmalary",
    ),
    _row(
        "E00-E90",
        "Класс IV. Болезни эндокринной системы, расстройства питания и нарушения обмена веществ",
        "Chapter IV. Endocrine, nutritional and metabolic diseases",
        kind=_SECTION_KIND,
        uk="Клас IV. Хвороби ендокринної системи, розлади харчування та порушення обміну речовин",
        be="Клас IV. Хваробы эндакрыннай сістэмы, расстройствы харчавання і парушэнні абмену рэчываў",
        kk="IV класс. Эндокриндік жүйе аурулары, тамақтану және зат алмасу бұзылыстары",
        uz="IV sinf. Endokrin tizim kasalliklari, ovqatlanish va modda almashinuvi buzilishlari",
        az="IV sinif. Endokrin sistem xəstəlikləri, qidalanma və maddələr mübadiləsi pozğunluqları",
        hy="IV դաս. Էնդոկրին համակարգի, սնուցման և նյութափոխանակության խանգարումներ",
        ka="IV კლასი. ენდოკრინული სისტემის, კვებისა და ნივთიერებათა ცვლის დარღვევები",
        tg="Синфи IV. Бемориҳои эндокринӣ, ихтилолҳои ғизо ва мубодилаи моддаҳо",
        tk="IV synp. Endokrin ulgam, iýmitleniş we madda çalşygy bozulmalary",
    ),
    _row(
        "F00-F99",
        "Класс V. Психические расстройства и расстройства поведения",
        "Chapter V. Mental and behavioural disorders",
        kind=_SECTION_KIND,
        uk="Клас V. Психічні та поведінкові розлади",
        be="Клас V. Псіхічныя і паводзінскія расстройствы",
        kk="V класс. Психикалық және мінез-құлық бұзылыстары",
        uz="V sinf. Ruhiy va xulq-atvor buzilishlari",
        az="V sinif. Psixi və davranış pozğunluqları",
        hy="V դաս. Հոգեկան և վարքային խանգարումներ",
        ka="V კლასი. ფსიქიკური და ქცევითი აშლილობები",
        tg="Синфи V. Ихтилолҳои рӯҳӣ ва рафторӣ",
        tk="V synp. Ruhy we özüni alyp baryş bozulmalary",
    ),
    _row(
        "G00-G99",
        "Класс VI. Болезни нервной системы",
        "Chapter VI. Diseases of the nervous system",
        kind=_SECTION_KIND,
        uk="Клас VI. Хвороби нервової системи",
        be="Клас VI. Хваробы нервовай сістэмы",
        kk="VI класс. Жүйке жүйесінің аурулары",
        uz="VI sinf. Asab tizimi kasalliklari",
        az="VI sinif. Sinir sistemi xəstəlikləri",
        hy="VI դաս. Նյարդային համակարգի հիվանդություններ",
        ka="VI კლასი. ნერვული სისტემის დაავადებები",
        tg="Синфи VI. Бемориҳои системаи асаб",
        tk="VI synp. Nerw ulgamynyň keselleri",
    ),
    _row(
        "H00-H59",
        "Класс VII. Болезни глаза и его придаточного аппарата",
        "Chapter VII. Diseases of the eye and adnexa",
        kind=_SECTION_KIND,
        uk="Клас VII. Хвороби ока та його придаткового апарату",
        be="Клас VII. Хваробы вока і яго прыдаткавага апарату",
        kk="VII класс. Көз және оның қосалқы аппаратының аурулары",
        uz="VII sinf. Ko‘z va uning qo‘shimcha apparati kasalliklari",
        az="VII sinif. Göz və onun əlavə aparatının xəstəlikləri",
        hy="VII դաս. Աչքի և հավելյալ ապարատի հիվանդություններ",
        ka="VII კლასი. თვალისა და მისი დანამატების დაავადებები",
        tg="Синфи VII. Бемориҳои чашм ва замимаҳои он",
        tk="VII synp. Göz we onuň goşmaça agzalarynyň keselleri",
    ),
    _row(
        "H60-H95",
        "Класс VIII. Болезни уха и сосцевидного отростка",
        "Chapter VIII. Diseases of the ear and mastoid process",
        kind=_SECTION_KIND,
        uk="Клас VIII. Хвороби вуха та соскоподібного відростка",
        be="Клас VIII. Хваробы вуха і соскападобнага адростка",
        kk="VIII класс. Құлақ және емізік тәрізді өсінді аурулары",
        uz="VIII sinf. Quloq va so‘rg‘ichsimon o‘simta kasalliklari",
        az="VIII sinif. Qulaq və məməciyəbənzər çıxıntı xəstəlikləri",
        hy="VIII դաս. Ականջի և պտկաձև ելունի հիվանդություններ",
        ka="VIII კლასი. ყურისა და დვრილისებრი მორჩის დაავადებები",
        tg="Синфи VIII. Бемориҳои гӯш ва шохаи пистоншакл",
        tk="VIII synp. Gulak we emzik görnüşli ösüntgi keselleri",
    ),
    _row(
        "I00-I99",
        "Класс IX. Болезни системы кровообращения",
        "Chapter IX. Diseases of the circulatory system",
        kind=_SECTION_KIND,
        uk="Клас IX. Хвороби системи кровообігу",
        be="Клас IX. Хваробы сістэмы кровазвароту",
        kk="IX класс. Қанайналым жүйесінің аурулары",
        uz="IX sinf. Qon aylanish tizimi kasalliklari",
        az="IX sinif. Qan dövranı sistemi xəstəlikləri",
        hy="IX դաս. Արյան շրջանառության համակարգի հիվանդություններ",
        ka="IX კლასი. სისხლის მიმოქცევის სისტემის დაავადებები",
        tg="Синфи IX. Бемориҳои системаи гардиши хун",
        tk="IX synp. Gan aýlanyş ulgamynyň keselleri",
    ),
    _row(
        "J00-J99",
        "Класс X. Болезни органов дыхания",
        "Chapter X. Diseases of the respiratory system",
        kind=_SECTION_KIND,
        uk="Клас X. Хвороби органів дихання",
        be="Клас X. Хваробы органаў дыхання",
        kk="X класс. Тыныс алу ағзаларының аурулары",
        uz="X sinf. Nafas olish a’zolari kasalliklari",
        az="X sinif. Tənəffüs sistemi xəstəlikləri",
        hy="X դաս. Շնչառական օրգանների հիվանդություններ",
        ka="X კლასი. სასუნთქი სისტემის დაავადებები",
        tg="Синфи X. Бемориҳои узвҳои нафаскашӣ",
        tk="X synp. Dem alyş agzalarynyň keselleri",
    ),
    _row(
        "K00-K93",
        "Класс XI. Болезни органов пищеварения",
        "Chapter XI. Diseases of the digestive system",
        kind=_SECTION_KIND,
        uk="Клас XI. Хвороби органів травлення",
        be="Клас XI. Хваробы органаў стрававання",
        kk="XI класс. Ас қорыту ағзаларының аурулары",
        uz="XI sinf. Ovqat hazm qilish a’zolari kasalliklari",
        az="XI sinif. Həzm sistemi xəstəlikləri",
        hy="XI դաս. Մարսողական օրգանների հիվանդություններ",
        ka="XI კლასი. საჭმლის მომნელებელი სისტემის დაავადებები",
        tg="Синфи XI. Бемориҳои узвҳои ҳозима",
        tk="XI synp. Iýmit siňdiriş agzalarynyň keselleri",
    ),
    _row(
        "L00-L99",
        "Класс XII. Болезни кожи и подкожной клетчатки",
        "Chapter XII. Diseases of the skin and subcutaneous tissue",
        kind=_SECTION_KIND,
        uk="Клас XII. Хвороби шкіри та підшкірної клітковини",
        be="Клас XII. Хваробы скуры і падскурнай клятчаткі",
        kk="XII класс. Тері және теріасты шелінің аурулары",
        uz="XII sinf. Teri va teri osti to‘qimasi kasalliklari",
        az="XII sinif. Dəri və dərialtı toxuma xəstəlikləri",
        hy="XII դաս. Մաշկի և ենթամաշկային բջջանքի հիվանդություններ",
        ka="XII კლასი. კანისა და კანქვეშა ქსოვილის დაავადებები",
        tg="Синфи XII. Бемориҳои пӯст ва бофтаи зери пӯст",
        tk="XII synp. Deri we deriasty dokuma keselleri",
    ),
    _row(
        "M00-M99",
        "Класс XIII. Болезни костно-мышечной системы и соединительной ткани",
        "Chapter XIII. Diseases of the musculoskeletal system and connective tissue",
        kind=_SECTION_KIND,
        uk="Клас XIII. Хвороби кістково-м’язової системи та сполучної тканини",
        be="Клас XIII. Хваробы касцёва-мышачнай сістэмы і злучальнай тканкі",
        kk="XIII класс. Сүйек-бұлшықет жүйесі және дәнекер тін аурулары",
        uz="XIII sinf. Suyak-mushak tizimi va biriktiruvchi to‘qima kasalliklari",
        az="XIII sinif. Sümük-əzələ sistemi və birləşdirici toxuma xəstəlikləri",
        hy="XIII դաս. Ոսկրամկանային համակարգի և շարակցական հյուսվածքի հիվանդություններ",
        ka="XIII კლასი. ძვალ-კუნთოვანი სისტემისა და შემაერთებელი ქსოვილის დაავადებები",
        tg="Синфи XIII. Бемориҳои устухон-мушак ва бофтаи пайвасткунанда",
        tk="XIII synp. Süňk-myşsa ulgamy we birleşdiriji dokuma keselleri",
    ),
    _row(
        "N00-N99",
        "Класс XIV. Болезни мочеполовой системы",
        "Chapter XIV. Diseases of the genitourinary system",
        kind=_SECTION_KIND,
        uk="Клас XIV. Хвороби сечостатевої системи",
        be="Клас XIV. Хваробы мочапалавой сістэмы",
        kk="XIV класс. Несеп-жыныс жүйесінің аурулары",
        uz="XIV sinf. Siydik-tanosil tizimi kasalliklari",
        az="XIV sinif. Sidik-cinsiyyət sistemi xəstəlikləri",
        hy="XIV դաս. Միզասեռական համակարգի հիվանդություններ",
        ka="XIV კლასი. შარდსასქესო სისტემის დაავადებები",
        tg="Синфи XIV. Бемориҳои системаи пешобу ҷинсӣ",
        tk="XIV synp. Peşew-jyns ulgamynyň keselleri",
    ),
    _row(
        "O00-O99",
        "Класс XV. Беременность, роды и послеродовой период",
        "Chapter XV. Pregnancy, childbirth and the puerperium",
        kind=_SECTION_KIND,
        uk="Клас XV. Вагітність, пологи та післяпологовий період",
        be="Клас XV. Цяжарнасць, роды і пасляродавы перыяд",
        kk="XV класс. Жүктілік, босану және босанғаннан кейінгі кезең",
        uz="XV sinf. Homiladorlik, tug‘ruq va tug‘ruqdan keyingi davr",
        az="XV sinif. Hamiləlik, doğuş və doğuşdan sonrakı dövr",
        hy="XV դաս. Հղիություն, ծննդաբերություն և հետծննդյան շրջան",
        ka="XV კლასი. ორსულობა, მშობიარობა და მშობიარობის შემდგომი პერიოდი",
        tg="Синфи XV. Ҳомиладорӣ, таваллуд ва давраи баъди таваллуд",
        tk="XV synp. Göwrelilik, dogrum we dogrumdan soňky döwür",
    ),
    _row(
        "P00-P96",
        "Класс XVI. Отдельные состояния, возникающие в перинатальном периоде",
        "Chapter XVI. Certain conditions originating in the perinatal period",
        kind=_SECTION_KIND,
        uk="Клас XVI. Окремі стани, що виникають у перинатальному періоді",
        be="Клас XVI. Асобныя станы, што ўзнікаюць у перынатальным перыядзе",
        kk="XVI класс. Перинаталдық кезеңде пайда болатын жекелеген жағдайлар",
        uz="XVI sinf. Perinatal davrda yuzaga keladigan ayrim holatlar",
        az="XVI sinif. Perinatal dövrdə yaranan bəzi hallar",
        hy="XVI դաս. Պերինատալ շրջանում առաջացող առանձին վիճակներ",
        ka="XVI კლასი. პერინატალურ პერიოდში წარმოშობილი ზოგიერთი მდგომარეობა",
        tg="Синфи XVI. Баъзе ҳолатҳо дар давраи перинаталӣ",
        tk="XVI synp. Perinatal döwürde döreýän käbir ýagdaýlar",
    ),
    _row(
        "Q00-Q99",
        "Класс XVII. Врожденные аномалии, деформации и хромосомные нарушения",
        "Chapter XVII. Congenital malformations, deformations and chromosomal abnormalities",
        kind=_SECTION_KIND,
        uk="Клас XVII. Вроджені аномалії, деформації та хромосомні порушення",
        be="Клас XVII. Прыроджаныя анамаліі, дэфармацыі і храмасомныя парушэнні",
        kk="XVII класс. Туа біткен аномалиялар, деформациялар және хромосомалық бұзылыстар",
        uz="XVII sinf. Tug‘ma anomaliyalar, deformatsiyalar va xromosoma buzilishlari",
        az="XVII sinif. Anadangəlmə anomaliyalar, deformasiyalar və xromosom pozğunluqları",
        hy="XVII դաս. Բնածին արատներ, դեֆորմացիաներ և քրոմոսոմային խանգարումներ",
        ka="XVII კლასი. თანდაყოლილი ანომალიები, დეფორმაციები და ქრომოსომული დარღვევები",
        tg="Синфи XVII. Нуқсонҳои модарзодӣ, деформатсияҳо ва ихтилолҳои хромосомӣ",
        tk="XVII synp. Dogabitdi anomaliýalar, deformasiýalar we hromosoma bozulmalary",
    ),
    _row(
        "R00-R99",
        "Класс XVIII. Симптомы, признаки и отклонения от нормы, выявленные при клинических и лабораторных исследованиях",
        "Chapter XVIII. Symptoms, signs and abnormal clinical and laboratory findings",
        kind=_SECTION_KIND,
        uk="Клас XVIII. Симптоми, ознаки та відхилення від норми, виявлені під час клінічних і лабораторних досліджень",
        be="Клас XVIII. Сімптомы, прыкметы і адхіленні ад нормы, выяўленыя пры клінічных і лабараторных даследаваннях",
        kk="XVIII класс. Клиникалық және зертханалық зерттеулерде анықталған симптомдар, белгілер және нормадан ауытқулар",
        uz="XVIII sinf. Klinik va laborator tekshiruvlarda aniqlangan simptomlar, belgilar va me’yordan og‘ishlar",
        az="XVIII sinif. Klinik və laborator müayinələrdə aşkar edilən simptomlar, əlamətlər və normadan kənar tapıntılar",
        hy="XVIII դաս. Կլինիկական և լաբորատոր հետազոտություններով հայտնաբերված ախտանիշներ, նշաններ և շեղումներ",
        ka="XVIII კლასი. კლინიკურ და ლაბორატორიულ გამოკვლევებში გამოვლენილი სიმპტომები, ნიშნები და გადახრები",
        tg="Синфи XVIII. Аломатҳо, нишонаҳо ва натиҷаҳои ғайримуқаррарии клиникӣ ва лабораторӣ",
        tk="XVIII synp. Kliniki we laborator barlaglarda ýüze çykarylan alamatlar, belgiler we kadadan gyşarmalar",
    ),
    _row(
        "S00-T98",
        "Класс XIX. Травмы, отравления и некоторые другие последствия воздействия внешних причин",
        "Chapter XIX. Injury, poisoning and certain other consequences of external causes",
        kind=_SECTION_KIND,
        uk="Клас XIX. Травми, отруєння та деякі інші наслідки дії зовнішніх причин",
        be="Клас XIX. Траўмы, атручванні і некаторыя іншыя наступствы ўздзеяння знешніх прычын",
        kk="XIX класс. Жарақаттар, уланулар және сыртқы себептердің кейбір басқа салдары",
        uz="XIX sinf. Jarohatlar, zaharlanishlar va tashqi sabablarning boshqa ayrim oqibatlari",
        az="XIX sinif. Travmalar, zəhərlənmələr və xarici səbəblərin bəzi digər nəticələri",
        hy="XIX դաս. Վնասվածքներ, թունավորումներ և արտաքին պատճառների այլ հետևանքներ",
        ka="XIX კლასი. ტრავმები, მოწამვლები და გარე მიზეზების სხვა შედეგები",
        tg="Синфи XIX. Осебҳо, заҳролудшавӣ ва баъзе дигар оқибатҳои таъсири сабабҳои беруна",
        tk="XIX synp. Şikesler, zäherlenmeler we daşarky sebäpleriň käbir beýleki netijeleri",
    ),
    _row(
        "V01-Y98",
        "Класс XX. Внешние причины заболеваемости и смертности",
        "Chapter XX. External causes of morbidity and mortality",
        kind=_SECTION_KIND,
        uk="Клас XX. Зовнішні причини захворюваності та смертності",
        be="Клас XX. Знешнія прычыны захворвання і смяротнасці",
        kk="XX класс. Аурушаңдық пен өлім-жітімнің сыртқы себептері",
        uz="XX sinf. Kasallanish va o‘limning tashqi sabablari",
        az="XX sinif. Xəstələnmə və ölümün xarici səbəbləri",
        hy="XX դաս. Հիվանդացության և մահացության արտաքին պատճառներ",
        ka="XX კლასი. ავადობისა და სიკვდილიანობის გარე მიზეზები",
        tg="Синфи XX. Сабабҳои берунии беморӣ ва фавт",
        tk="XX synp. Keselleýişiň we ölümçiligiň daşarky sebäpleri",
    ),
    _row(
        "Z00-Z99",
        "Класс XXI. Факторы, влияющие на состояние здоровья и обращения в учреждения здравоохранения",
        "Chapter XXI. Factors influencing health status and contact with health services",
        kind=_SECTION_KIND,
        uk="Клас XXI. Фактори, що впливають на стан здоров’я та звернення до закладів охорони здоров’я",
        be="Клас XXI. Фактары, што ўплываюць на стан здароўя і звароты ў медыцынскія ўстановы",
        kk="XXI класс. Денсаулық жағдайына әсер ететін факторлар және денсаулық сақтау ұйымдарына жүгіну",
        uz="XXI sinf. Salomatlik holatiga ta’sir qiluvchi omillar va tibbiyot muassasalariga murojaatlar",
        az="XXI sinif. Sağlamlıq vəziyyətinə təsir edən amillər və səhiyyə xidmətləri ilə əlaqə",
        hy="XXI դաս. Առողջական վիճակի վրա ազդող գործոններ և առողջապահական ծառայություններին դիմումներ",
        ka="XXI კლასი. ჯანმრთელობის მდგომარეობაზე მოქმედი ფაქტორები და ჯანდაცვის მომსახურებასთან კონტაქტი",
        tg="Синфи XXI. Омилҳое, ки ба вазъи саломатӣ таъсир мерасонанд ва муроҷиат ба муассисаҳои тандурустӣ",
        tk="XXI synp. Saglyk ýagdaýyna täsir edýän faktorlar we saglygy goraýyş hyzmatlaryna ýüz tutmak",
    ),
    _row(
        "U00-U99",
        "Класс XXII. Коды для особых целей",
        "Chapter XXII. Codes for special purposes",
        kind=_SECTION_KIND,
        uk="Клас XXII. Коди для спеціальних цілей",
        be="Клас XXII. Коды для спецыяльных мэт",
        kk="XXII класс. Арнайы мақсаттарға арналған кодтар",
        uz="XXII sinf. Maxsus maqsadlar uchun kodlar",
        az="XXII sinif. Xüsusi məqsədlər üçün kodlar",
        hy="XXII դաս. Հատուկ նպատակների համար կոդեր",
        ka="XXII კლასი. კოდები სპეციალური მიზნებისთვის",
        tg="Синфи XXII. Кодҳо барои мақсадҳои махсус",
        tk="XXII synp. Ýörite maksatlar üçin kodlar",
    ),
]


_BLOCK_ROWS: list[ICD10Diagnosis] = [
    _row("A00-A09", "Кишечные инфекционные болезни", "Intestinal infectious diseases", kind=_BLOCK_KIND),
    _row("A15-A19", "Туберкулёз", "Tuberculosis", kind=_BLOCK_KIND),
    _row("A20-A28", "Некоторые бактериальные зоонозы", "Certain zoonotic bacterial diseases", kind=_BLOCK_KIND),
    _row("A30-A49", "Другие бактериальные болезни", "Other bacterial diseases", kind=_BLOCK_KIND),
    _row("A50-A64", "Инфекции, передающиеся преимущественно половым путём", "Infections with a predominantly sexual mode of transmission", kind=_BLOCK_KIND),
    _row("A65-A69", "Другие спирохетозы", "Other spirochaetal diseases", kind=_BLOCK_KIND),
    _row("A70-A74", "Другие болезни, вызываемые хламидиями", "Other diseases caused by chlamydiae", kind=_BLOCK_KIND),
    _row("A75-A79", "Риккетсиозы", "Rickettsioses", kind=_BLOCK_KIND),
    _row("A80-A89", "Вирусные инфекции центральной нервной системы", "Viral infections of the central nervous system", kind=_BLOCK_KIND),
    _row("A90-A99", "Вирусные лихорадки и вирусные геморрагические лихорадки", "Arthropod-borne viral fevers and viral haemorrhagic fevers", kind=_BLOCK_KIND),
    _row("B00-B09", "Вирусные инфекции кожи и слизистых оболочек", "Viral infections characterized by skin and mucous membrane lesions", kind=_BLOCK_KIND),
    _row("B15-B19", "Вирусный гепатит", "Viral hepatitis", kind=_BLOCK_KIND),
    _row("B20-B24", "Болезнь, вызванная вирусом иммунодефицита человека", "Human immunodeficiency virus disease", kind=_BLOCK_KIND),
    _row("B25-B34", "Другие вирусные болезни", "Other viral diseases", kind=_BLOCK_KIND),
    _row("B35-B49", "Микозы", "Mycoses", kind=_BLOCK_KIND),
    _row("B50-B64", "Протозойные болезни", "Protozoal diseases", kind=_BLOCK_KIND),
    _row("B65-B83", "Гельминтозы", "Helminthiases", kind=_BLOCK_KIND),
    _row("B85-B89", "Педикулёз, акариаз и другие инфестации", "Pediculosis, acariasis and other infestations", kind=_BLOCK_KIND),
    _row("B90-B94", "Последствия инфекционных и паразитарных болезней", "Sequelae of infectious and parasitic diseases", kind=_BLOCK_KIND),
    _row("B95-B98", "Бактериальные, вирусные и другие инфекционные агенты", "Bacterial, viral and other infectious agents", kind=_BLOCK_KIND),
    _row("B99-B99", "Другие инфекционные болезни", "Other infectious diseases", kind=_BLOCK_KIND),
    _row("C00-C14", "Злокачественные новообразования губы, полости рта и глотки", "Malignant neoplasms of lip, oral cavity and pharynx", kind=_BLOCK_KIND),
    _row("C15-C26", "Злокачественные новообразования органов пищеварения", "Malignant neoplasms of digestive organs", kind=_BLOCK_KIND),
    _row("C30-C39", "Злокачественные новообразования органов дыхания и грудной клетки", "Malignant neoplasms of respiratory and intrathoracic organs", kind=_BLOCK_KIND),
    _row("C40-C41", "Злокачественные новообразования костей и суставных хрящей", "Malignant neoplasms of bone and articular cartilage", kind=_BLOCK_KIND),
    _row("C43-C44", "Меланома и другие злокачественные новообразования кожи", "Melanoma and other malignant neoplasms of skin", kind=_BLOCK_KIND),
    _row("C45-C49", "Злокачественные новообразования мезотелиальной и мягких тканей", "Malignant neoplasms of mesothelial and soft tissue", kind=_BLOCK_KIND),
    _row("C50-C50", "Злокачественное новообразование молочной железы", "Malignant neoplasm of breast", kind=_BLOCK_KIND),
    _row("C51-C58", "Злокачественные новообразования женских половых органов", "Malignant neoplasms of female genital organs", kind=_BLOCK_KIND),
    _row("C60-C63", "Злокачественные новообразования мужских половых органов", "Malignant neoplasms of male genital organs", kind=_BLOCK_KIND),
    _row("C64-C68", "Злокачественные новообразования мочевых путей", "Malignant neoplasms of urinary tract", kind=_BLOCK_KIND),
    _row("C69-C72", "Злокачественные новообразования глаза, головного мозга и других отделов ЦНС", "Malignant neoplasms of eye, brain and other parts of CNS", kind=_BLOCK_KIND),
    _row("C73-C75", "Злокачественные новообразования щитовидной и других эндокринных желез", "Malignant neoplasms of thyroid and other endocrine glands", kind=_BLOCK_KIND),
    _row("C76-C80", "Злокачественные новообразования неточно обозначенных, вторичных и неуточнённых локализаций", "Malignant neoplasms of ill-defined, secondary and unspecified sites", kind=_BLOCK_KIND),
    _row("C81-C96", "Злокачественные новообразования лимфоидной, кроветворной и родственных тканей", "Malignant neoplasms of lymphoid, haematopoietic and related tissue", kind=_BLOCK_KIND),
    _row("C97-C97", "Злокачественные новообразования самостоятельных множественных локализаций", "Malignant neoplasms of independent multiple sites", kind=_BLOCK_KIND),
    _row("D00-D09", "Новообразования in situ", "In situ neoplasms", kind=_BLOCK_KIND),
    _row("D10-D36", "Доброкачественные новообразования", "Benign neoplasms", kind=_BLOCK_KIND),
    _row("D37-D48", "Новообразования неопределённого или неизвестного характера", "Neoplasms of uncertain or unknown behaviour", kind=_BLOCK_KIND),
    _row("D50-D53", "Анемии, связанные с питанием", "Nutritional anaemias", kind=_BLOCK_KIND),
    _row("D55-D59", "Гемолитические анемии", "Haemolytic anaemias", kind=_BLOCK_KIND),
    _row("D60-D64", "Апластические и другие анемии", "Aplastic and other anaemias", kind=_BLOCK_KIND),
    _row("D65-D69", "Нарушения свёртывания крови, пурпура и другие геморрагические состояния", "Coagulation defects, purpura and other haemorrhagic conditions", kind=_BLOCK_KIND),
    _row("D70-D77", "Другие болезни крови и кроветворных органов", "Other diseases of blood and blood-forming organs", kind=_BLOCK_KIND),
    _row("D80-D89", "Отдельные нарушения иммунного механизма", "Certain disorders involving the immune mechanism", kind=_BLOCK_KIND),
    _row("E00-E07", "Болезни щитовидной железы", "Disorders of thyroid gland", kind=_BLOCK_KIND),
    _row("E10-E14", "Сахарный диабет", "Diabetes mellitus", kind=_BLOCK_KIND),
    _row("E15-E16", "Другие нарушения регуляции глюкозы и внутренней секреции поджелудочной железы", "Other disorders of glucose regulation and pancreatic internal secretion", kind=_BLOCK_KIND),
    _row("E20-E35", "Нарушения других эндокринных желез", "Disorders of other endocrine glands", kind=_BLOCK_KIND),
    _row("E40-E46", "Недостаточность питания", "Malnutrition", kind=_BLOCK_KIND),
    _row("E50-E64", "Другие виды недостаточности питания", "Other nutritional deficiencies", kind=_BLOCK_KIND),
    _row("E65-E68", "Ожирение и другие виды избыточного питания", "Obesity and other hyperalimentation", kind=_BLOCK_KIND),
    _row("E70-E90", "Нарушения обмена веществ", "Metabolic disorders", kind=_BLOCK_KIND),
    _row("G00-G09", "Воспалительные болезни центральной нервной системы", "Inflammatory diseases of the central nervous system", kind=_BLOCK_KIND),
    _row("G10-G14", "Системные атрофии, поражающие преимущественно центральную нервную систему", "Systemic atrophies primarily affecting the central nervous system", kind=_BLOCK_KIND),
    _row("G20-G26", "Экстрапирамидные и двигательные нарушения", "Extrapyramidal and movement disorders", kind=_BLOCK_KIND),
    _row("G30-G32", "Другие дегенеративные болезни нервной системы", "Other degenerative diseases of the nervous system", kind=_BLOCK_KIND),
    _row("G35-G37", "Демиелинизирующие болезни центральной нервной системы", "Demyelinating diseases of the central nervous system", kind=_BLOCK_KIND),
    _row("G40-G47", "Эпизодические и пароксизмальные расстройства", "Episodic and paroxysmal disorders", kind=_BLOCK_KIND),
    _row("G50-G59", "Поражения отдельных нервов, нервных корешков и сплетений", "Nerve, nerve root and plexus disorders", kind=_BLOCK_KIND),
    _row("G60-G64", "Полиневропатии и другие поражения периферической нервной системы", "Polyneuropathies and other disorders of peripheral nervous system", kind=_BLOCK_KIND),
    _row("G70-G73", "Болезни нервно-мышечного синапса и мышц", "Diseases of myoneural junction and muscle", kind=_BLOCK_KIND),
    _row("G80-G83", "Церебральный паралич и другие паралитические синдромы", "Cerebral palsy and other paralytic syndromes", kind=_BLOCK_KIND),
    _row("G90-G99", "Другие нарушения нервной системы", "Other disorders of the nervous system", kind=_BLOCK_KIND),
    _row("H00-H06", "Болезни век, слёзных путей и глазницы", "Disorders of eyelid, lacrimal system and orbit", kind=_BLOCK_KIND),
    _row("H10-H13", "Болезни конъюнктивы", "Disorders of conjunctiva", kind=_BLOCK_KIND),
    _row("H15-H22", "Болезни склеры, роговицы, радужной оболочки и цилиарного тела", "Disorders of sclera, cornea, iris and ciliary body", kind=_BLOCK_KIND),
    _row("H25-H28", "Болезни хрусталика", "Disorders of lens", kind=_BLOCK_KIND),
    _row("H30-H36", "Болезни сосудистой оболочки и сетчатки", "Disorders of choroid and retina", kind=_BLOCK_KIND),
    _row("H40-H42", "Глаукома", "Glaucoma", kind=_BLOCK_KIND),
    _row("H43-H45", "Болезни стекловидного тела и глазного яблока", "Disorders of vitreous body and globe", kind=_BLOCK_KIND),
    _row("H46-H48", "Болезни зрительного нерва и зрительных путей", "Disorders of optic nerve and visual pathways", kind=_BLOCK_KIND),
    _row("H49-H52", "Болезни мышц глаза, нарушения содружественного движения глаз, аккомодации и рефракции", "Disorders of ocular muscles, binocular movement, accommodation and refraction", kind=_BLOCK_KIND),
    _row("H53-H54", "Зрительные расстройства и слепота", "Visual disturbances and blindness", kind=_BLOCK_KIND),
    _row("H55-H59", "Другие болезни глаза и его придаточного аппарата", "Other disorders of eye and adnexa", kind=_BLOCK_KIND),
    _row("H60-H62", "Болезни наружного уха", "Diseases of external ear", kind=_BLOCK_KIND),
    _row("H65-H75", "Болезни среднего уха и сосцевидного отростка", "Diseases of middle ear and mastoid", kind=_BLOCK_KIND),
    _row("H80-H83", "Болезни внутреннего уха", "Diseases of inner ear", kind=_BLOCK_KIND),
    _row("H90-H95", "Другие болезни уха", "Other disorders of ear", kind=_BLOCK_KIND),
    _row("I00-I02", "Острая ревматическая лихорадка", "Acute rheumatic fever", kind=_BLOCK_KIND),
    _row("I05-I09", "Хронические ревматические болезни сердца", "Chronic rheumatic heart diseases", kind=_BLOCK_KIND),
    _row("I10-I15", "Гипертензивные болезни", "Hypertensive diseases", kind=_BLOCK_KIND),
    _row("I20-I25", "Ишемические болезни сердца", "Ischaemic heart diseases", kind=_BLOCK_KIND),
    _row("I26-I28", "Лёгочное сердце и нарушения лёгочного кровообращения", "Pulmonary heart disease and diseases of pulmonary circulation", kind=_BLOCK_KIND),
    _row("I30-I52", "Другие болезни сердца", "Other forms of heart disease", kind=_BLOCK_KIND),
    _row("I60-I69", "Цереброваскулярные болезни", "Cerebrovascular diseases", kind=_BLOCK_KIND),
    _row("I70-I79", "Болезни артерий, артериол и капилляров", "Diseases of arteries, arterioles and capillaries", kind=_BLOCK_KIND),
    _row("I80-I89", "Болезни вен, лимфатических сосудов и лимфатических узлов", "Diseases of veins, lymphatic vessels and lymph nodes", kind=_BLOCK_KIND),
    _row("I95-I99", "Другие и неуточнённые болезни системы кровообращения", "Other and unspecified disorders of the circulatory system", kind=_BLOCK_KIND),
    _row("J00-J06", "Острые респираторные инфекции верхних дыхательных путей", "Acute upper respiratory infections", kind=_BLOCK_KIND),
    _row("J09-J18", "Грипп и пневмония", "Influenza and pneumonia", kind=_BLOCK_KIND),
    _row("J20-J22", "Другие острые респираторные инфекции нижних дыхательных путей", "Other acute lower respiratory infections", kind=_BLOCK_KIND),
    _row("J30-J39", "Другие болезни верхних дыхательных путей", "Other diseases of upper respiratory tract", kind=_BLOCK_KIND),
    _row("J40-J47", "Хронические болезни нижних дыхательных путей", "Chronic lower respiratory diseases", kind=_BLOCK_KIND),
    _row("J60-J70", "Болезни лёгких, вызванные внешними агентами", "Lung diseases due to external agents", kind=_BLOCK_KIND),
    _row("J80-J84", "Другие респираторные болезни, поражающие интерстициальную ткань", "Other respiratory diseases principally affecting the interstitium", kind=_BLOCK_KIND),
    _row("J85-J86", "Гнойные и некротические состояния нижних дыхательных путей", "Suppurative and necrotic conditions of lower respiratory tract", kind=_BLOCK_KIND),
    _row("J90-J94", "Другие болезни плевры", "Other diseases of pleura", kind=_BLOCK_KIND),
    _row("J95-J99", "Другие болезни органов дыхания", "Other diseases of the respiratory system", kind=_BLOCK_KIND),
    _row("K00-K14", "Болезни полости рта, слюнных желёз и челюстей", "Diseases of oral cavity, salivary glands and jaws", kind=_BLOCK_KIND),
    _row("K20-K31", "Болезни пищевода, желудка и двенадцатиперстной кишки", "Diseases of oesophagus, stomach and duodenum", kind=_BLOCK_KIND),
    _row("K35-K38", "Болезни аппендикса", "Diseases of appendix", kind=_BLOCK_KIND),
    _row("K40-K46", "Грыжи", "Hernia", kind=_BLOCK_KIND),
    _row("K50-K52", "Неинфекционный энтерит и колит", "Noninfective enteritis and colitis", kind=_BLOCK_KIND),
    _row("K55-K64", "Другие болезни кишечника", "Other diseases of intestines", kind=_BLOCK_KIND),
    _row("K65-K67", "Болезни брюшины", "Diseases of peritoneum", kind=_BLOCK_KIND),
    _row("K70-K77", "Болезни печени", "Diseases of liver", kind=_BLOCK_KIND),
    _row("K80-K87", "Болезни желчного пузыря, желчевыводящих путей и поджелудочной железы", "Disorders of gallbladder, biliary tract and pancreas", kind=_BLOCK_KIND),
    _row("K90-K93", "Другие болезни органов пищеварения", "Other diseases of the digestive system", kind=_BLOCK_KIND),
    _row("L00-L08", "Инфекции кожи и подкожной клетчатки", "Infections of the skin and subcutaneous tissue", kind=_BLOCK_KIND),
    _row("L10-L14", "Буллёзные нарушения", "Bullous disorders", kind=_BLOCK_KIND),
    _row("L20-L30", "Дерматит и экзема", "Dermatitis and eczema", kind=_BLOCK_KIND),
    _row("L40-L45", "Папулосквамозные нарушения", "Papulosquamous disorders", kind=_BLOCK_KIND),
    _row("L50-L54", "Крапивница и эритема", "Urticaria and erythema", kind=_BLOCK_KIND),
    _row("L55-L59", "Болезни кожи и подкожной клетчатки, связанные с излучением", "Radiation-related disorders of the skin and subcutaneous tissue", kind=_BLOCK_KIND),
    _row("L60-L75", "Болезни придатков кожи", "Disorders of skin appendages", kind=_BLOCK_KIND),
    _row("L80-L99", "Другие болезни кожи и подкожной клетчатки", "Other disorders of the skin and subcutaneous tissue", kind=_BLOCK_KIND),
    _row("M00-M25", "Артропатии", "Arthropathies", kind=_BLOCK_KIND),
    _row("M30-M36", "Системные поражения соединительной ткани", "Systemic connective tissue disorders", kind=_BLOCK_KIND),
    _row("M40-M54", "Дорсопатии", "Dorsopathies", kind=_BLOCK_KIND),
    _row("M60-M79", "Болезни мягких тканей", "Soft tissue disorders", kind=_BLOCK_KIND),
    _row("M80-M94", "Остеопатии и хондропатии", "Osteopathies and chondropathies", kind=_BLOCK_KIND),
    _row("M95-M99", "Другие нарушения костно-мышечной системы и соединительной ткани", "Other disorders of the musculoskeletal system and connective tissue", kind=_BLOCK_KIND),
    _row("N00-N08", "Гломерулярные болезни", "Glomerular diseases", kind=_BLOCK_KIND),
    _row("N10-N16", "Тубулоинтерстициальные болезни почек", "Renal tubulo-interstitial diseases", kind=_BLOCK_KIND),
    _row("N17-N19", "Почечная недостаточность", "Renal failure", kind=_BLOCK_KIND),
    _row("N20-N23", "Мочекаменная болезнь", "Urolithiasis", kind=_BLOCK_KIND),
    _row("N25-N29", "Другие болезни почки и мочеточника", "Other disorders of kidney and ureter", kind=_BLOCK_KIND),
    _row("N30-N39", "Другие болезни мочевой системы", "Other diseases of urinary system", kind=_BLOCK_KIND),
    _row("N40-N51", "Болезни мужских половых органов", "Diseases of male genital organs", kind=_BLOCK_KIND),
    _row("N60-N64", "Болезни молочной железы", "Disorders of breast", kind=_BLOCK_KIND),
    _row("N70-N77", "Воспалительные болезни женских тазовых органов", "Inflammatory diseases of female pelvic organs", kind=_BLOCK_KIND),
    _row("N80-N98", "Невоспалительные болезни женских половых органов", "Noninflammatory disorders of female genital tract", kind=_BLOCK_KIND),
    _row("N99-N99", "Другие нарушения мочеполовой системы", "Other disorders of genitourinary system", kind=_BLOCK_KIND),
    _row("O00-O08", "Беременность с абортивным исходом", "Pregnancy with abortive outcome", kind=_BLOCK_KIND),
    _row("O10-O16", "Отеки, протеинурия и гипертензивные расстройства при беременности, родах и послеродовом периоде", "Oedema, proteinuria and hypertensive disorders in pregnancy, childbirth and puerperium", kind=_BLOCK_KIND),
    _row("O20-O29", "Другие болезни матери, преимущественно связанные с беременностью", "Other maternal disorders predominantly related to pregnancy", kind=_BLOCK_KIND),
    _row("O30-O48", "Медицинская помощь матери в связи с плодом, амниотической полостью и возможными проблемами родоразрешения", "Maternal care related to fetus, amniotic cavity and possible delivery problems", kind=_BLOCK_KIND),
    _row("O60-O75", "Осложнения родов и родоразрешения", "Complications of labour and delivery", kind=_BLOCK_KIND),
    _row("O80-O84", "Родоразрешение", "Delivery", kind=_BLOCK_KIND),
    _row("O85-O92", "Осложнения, преимущественно связанные с послеродовым периодом", "Complications predominantly related to the puerperium", kind=_BLOCK_KIND),
    _row("O94-O99", "Другие акушерские состояния", "Other obstetric conditions", kind=_BLOCK_KIND),
    _row("P00-P04", "Поражения плода и новорождённого, обусловленные состояниями матери", "Fetus and newborn affected by maternal factors", kind=_BLOCK_KIND),
    _row("P05-P08", "Расстройства, связанные с продолжительностью беременности и ростом плода", "Disorders related to length of gestation and fetal growth", kind=_BLOCK_KIND),
    _row("P10-P15", "Родовая травма", "Birth trauma", kind=_BLOCK_KIND),
    _row("P20-P29", "Респираторные и сердечно-сосудистые нарушения перинатального периода", "Respiratory and cardiovascular disorders specific to perinatal period", kind=_BLOCK_KIND),
    _row("P35-P39", "Инфекционные болезни, специфичные для перинатального периода", "Infections specific to perinatal period", kind=_BLOCK_KIND),
    _row("P50-P61", "Геморрагические и гематологические нарушения у плода и новорождённого", "Haemorrhagic and haematological disorders of fetus and newborn", kind=_BLOCK_KIND),
    _row("P70-P74", "Преходящие эндокринные и метаболические нарушения у плода и новорождённого", "Transitory endocrine and metabolic disorders specific to fetus and newborn", kind=_BLOCK_KIND),
    _row("P75-P78", "Болезни пищеварительной системы у плода и новорождённого", "Digestive system disorders of fetus and newborn", kind=_BLOCK_KIND),
    _row("P80-P83", "Состояния, вовлекающие наружные покровы и терморегуляцию плода и новорождённого", "Conditions involving integument and temperature regulation of fetus and newborn", kind=_BLOCK_KIND),
    _row("P90-P96", "Другие нарушения перинатального периода", "Other disorders originating in the perinatal period", kind=_BLOCK_KIND),
    _row("Q00-Q07", "Врожденные аномалии нервной системы", "Congenital malformations of the nervous system", kind=_BLOCK_KIND),
    _row("Q10-Q18", "Врожденные аномалии глаза, уха, лица и шеи", "Congenital malformations of eye, ear, face and neck", kind=_BLOCK_KIND),
    _row("Q20-Q28", "Врожденные аномалии системы кровообращения", "Congenital malformations of circulatory system", kind=_BLOCK_KIND),
    _row("Q30-Q34", "Врожденные аномалии дыхательной системы", "Congenital malformations of respiratory system", kind=_BLOCK_KIND),
    _row("Q35-Q37", "Расщелина губы и нёба", "Cleft lip and cleft palate", kind=_BLOCK_KIND),
    _row("Q38-Q45", "Другие врожденные аномалии пищеварительной системы", "Other congenital malformations of digestive system", kind=_BLOCK_KIND),
    _row("Q50-Q56", "Врожденные аномалии половых органов", "Congenital malformations of genital organs", kind=_BLOCK_KIND),
    _row("Q60-Q64", "Врожденные аномалии мочевой системы", "Congenital malformations of urinary system", kind=_BLOCK_KIND),
    _row("Q65-Q79", "Врожденные аномалии и деформации костно-мышечной системы", "Congenital malformations and deformations of musculoskeletal system", kind=_BLOCK_KIND),
    _row("Q80-Q89", "Другие врожденные аномалии", "Other congenital malformations", kind=_BLOCK_KIND),
    _row("Q90-Q99", "Хромосомные аномалии", "Chromosomal abnormalities", kind=_BLOCK_KIND),
    _row("R00-R09", "Симптомы и признаки, относящиеся к системам кровообращения и дыхания", "Symptoms and signs involving circulatory and respiratory systems", kind=_BLOCK_KIND),
    _row("R10-R19", "Симптомы и признаки, относящиеся к системе пищеварения и брюшной полости", "Symptoms and signs involving digestive system and abdomen", kind=_BLOCK_KIND),
    _row("R20-R23", "Симптомы и признаки, относящиеся к коже и подкожной клетчатке", "Symptoms and signs involving skin and subcutaneous tissue", kind=_BLOCK_KIND),
    _row("R25-R29", "Симптомы и признаки, относящиеся к нервной и костно-мышечной системам", "Symptoms and signs involving nervous and musculoskeletal systems", kind=_BLOCK_KIND),
    _row("R30-R39", "Симптомы и признаки, относящиеся к мочевой системе", "Symptoms and signs involving urinary system", kind=_BLOCK_KIND),
    _row("R40-R46", "Симптомы и признаки, относящиеся к познавательной способности, восприятию, эмоциональному состоянию и поведению", "Symptoms and signs involving cognition, perception, emotional state and behaviour", kind=_BLOCK_KIND),
    _row("R47-R49", "Симптомы и признаки, относящиеся к речи и голосу", "Symptoms and signs involving speech and voice", kind=_BLOCK_KIND),
    _row("R50-R69", "Общие симптомы и признаки", "General symptoms and signs", kind=_BLOCK_KIND),
    _row("R70-R79", "Отклонения от нормы, выявленные при исследовании крови", "Abnormal findings on examination of blood", kind=_BLOCK_KIND),
    _row("R80-R82", "Отклонения от нормы, выявленные при исследовании мочи", "Abnormal findings on examination of urine", kind=_BLOCK_KIND),
    _row("R83-R89", "Отклонения от нормы, выявленные при исследовании других жидкостей, веществ и тканей", "Abnormal findings on examination of other body fluids, substances and tissues", kind=_BLOCK_KIND),
    _row("R90-R94", "Отклонения от нормы, выявленные при диагностической визуализации и функциональных исследованиях", "Abnormal findings on diagnostic imaging and function studies", kind=_BLOCK_KIND),
    _row("R95-R99", "Неточно обозначенные и неизвестные причины смерти", "Ill-defined and unknown causes of mortality", kind=_BLOCK_KIND),
    _row("S00-S09", "Травмы головы", "Injuries to the head", kind=_BLOCK_KIND),
    _row("S10-S19", "Травмы шеи", "Injuries to the neck", kind=_BLOCK_KIND),
    _row("S20-S29", "Травмы грудной клетки", "Injuries to the thorax", kind=_BLOCK_KIND),
    _row("S30-S39", "Травмы живота, нижней части спины, поясничного отдела позвоночника и таза", "Injuries to the abdomen, lower back, lumbar spine and pelvis", kind=_BLOCK_KIND),
    _row("S40-S49", "Травмы плечевого пояса и плеча", "Injuries to the shoulder and upper arm", kind=_BLOCK_KIND),
    _row("S50-S59", "Травмы локтя и предплечья", "Injuries to the elbow and forearm", kind=_BLOCK_KIND),
    _row("S60-S69", "Травмы запястья и кисти", "Injuries to the wrist and hand", kind=_BLOCK_KIND),
    _row("S70-S79", "Травмы области тазобедренного сустава и бедра", "Injuries to the hip and thigh", kind=_BLOCK_KIND),
    _row("S80-S89", "Травмы колена и голени", "Injuries to the knee and lower leg", kind=_BLOCK_KIND),
    _row("S90-S99", "Травмы голеностопного сустава и стопы", "Injuries to the ankle and foot", kind=_BLOCK_KIND),
    _row("T00-T07", "Травмы, захватывающие несколько областей тела", "Injuries involving multiple body regions", kind=_BLOCK_KIND),
    _row("T08-T14", "Травмы неуточнённой части туловища, конечности или области тела", "Injuries to unspecified part of trunk, limb or body region", kind=_BLOCK_KIND),
    _row("T15-T19", "Последствия проникновения инородного тела через естественное отверстие", "Effects of foreign body entering through natural orifice", kind=_BLOCK_KIND),
    _row("T20-T32", "Ожоги и отморожения", "Burns and corrosions", kind=_BLOCK_KIND),
    _row("T36-T50", "Отравления лекарственными средствами, медикаментами и биологическими веществами", "Poisoning by drugs, medicaments and biological substances", kind=_BLOCK_KIND),
    _row("T51-T65", "Токсическое действие веществ преимущественно немедицинского назначения", "Toxic effects of substances chiefly nonmedicinal as to source", kind=_BLOCK_KIND),
    _row("T66-T78", "Другие и неуточнённые эффекты внешних причин", "Other and unspecified effects of external causes", kind=_BLOCK_KIND),
    _row("T79-T79", "Некоторые ранние осложнения травм", "Certain early complications of trauma", kind=_BLOCK_KIND),
    _row("T80-T88", "Осложнения хирургических и терапевтических вмешательств", "Complications of surgical and medical care", kind=_BLOCK_KIND),
    _row("T90-T98", "Последствия травм, отравлений и других внешних причин", "Sequelae of injuries, poisoning and external causes", kind=_BLOCK_KIND),
    _row("V01-X59", "Несчастные случаи", "Accidents", kind=_BLOCK_KIND),
    _row("X60-X84", "Преднамеренное самоповреждение", "Intentional self-harm", kind=_BLOCK_KIND),
    _row("X85-Y09", "Нападение", "Assault", kind=_BLOCK_KIND),
    _row("Y10-Y34", "Событие с неопределёнными намерениями", "Event of undetermined intent", kind=_BLOCK_KIND),
    _row("Y35-Y36", "Действия, предусмотренные законом, и военные операции", "Legal intervention and operations of war", kind=_BLOCK_KIND),
    _row("Y40-Y84", "Осложнения медицинской помощи и хирургических вмешательств", "Complications of medical and surgical care", kind=_BLOCK_KIND),
    _row("Y85-Y89", "Последствия внешних причин заболеваемости и смертности", "Sequelae of external causes of morbidity and mortality", kind=_BLOCK_KIND),
    _row("Y90-Y98", "Дополнительные факторы, относящиеся к причинам заболеваемости и смертности", "Supplementary factors related to causes of morbidity and mortality", kind=_BLOCK_KIND),
    _row("Z00-Z13", "Обращения в медицинские учреждения для обследования и осмотра", "Persons encountering health services for examination and investigation", kind=_BLOCK_KIND),
    _row("Z20-Z29", "Потенциальная опасность для здоровья, связанная с инфекционными болезнями", "Persons with potential health hazards related to communicable diseases", kind=_BLOCK_KIND),
    _row("Z30-Z39", "Обращения, связанные с репродуктивной функцией", "Persons encountering health services in circumstances related to reproduction", kind=_BLOCK_KIND),
    _row("Z40-Z54", "Обращения в медицинские учреждения в связи со специфическими процедурами и медицинской помощью", "Persons encountering health services for specific procedures and health care", kind=_BLOCK_KIND),
    _row("Z55-Z65", "Потенциальная опасность для здоровья, связанная с социально-экономическими и психосоциальными обстоятельствами", "Persons with potential health hazards related to socioeconomic and psychosocial circumstances", kind=_BLOCK_KIND),
    _row("Z70-Z76", "Обращения в медицинские учреждения в связи с другими обстоятельствами", "Persons encountering health services in other circumstances", kind=_BLOCK_KIND),
    _row("Z80-Z99", "Потенциальная опасность для здоровья, связанная с семейным и личным анамнезом", "Persons with potential health hazards related to family and personal history", kind=_BLOCK_KIND),
    _row("U00-U49", "Временное назначение новых болезней неизвестной этиологии", "Provisional assignment of new diseases of uncertain etiology", kind=_BLOCK_KIND),
    _row("U50-U99", "Коды для исследований и особых целей", "Codes for research and special purposes", kind=_BLOCK_KIND),
]


_COMMON_RUBRIC_ROWS: list[ICD10Diagnosis] = [
    _row("A09", "Диарея и гастроэнтерит предположительно инфекционного происхождения", "Diarrhoea and gastroenteritis of presumed infectious origin"),
    _row("A15", "Туберкулёз органов дыхания, подтверждённый бактериологически и гистологически", "Respiratory tuberculosis, bacteriologically and histologically confirmed"),
    _row("B18", "Хронический вирусный гепатит", "Chronic viral hepatitis"),
    _row("B20", "Болезнь, вызванная вирусом иммунодефицита человека, проявляющаяся инфекционными и паразитарными болезнями", "HIV disease resulting in infectious and parasitic diseases"),
    _row("C34", "Злокачественное новообразование бронхов и лёгкого", "Malignant neoplasm of bronchus and lung"),
    _row("C50", "Злокачественное новообразование молочной железы", "Malignant neoplasm of breast"),
    _row("D64", "Другие анемии", "Other anaemias"),
    _row("E03", "Другие формы гипотиреоза", "Other hypothyroidism"),
    _row("E10", "Сахарный диабет 1 типа", "Type 1 diabetes mellitus"),
    _row("E11", "Сахарный диабет 2 типа", "Type 2 diabetes mellitus"),
    _row("E66", "Ожирение", "Obesity"),
    _row("G40", "Эпилепсия", "Epilepsy"),
    _row("G43", "Мигрень", "Migraine"),
    _row("H52", "Нарушения рефракции и аккомодации", "Disorders of refraction and accommodation"),
    _row("I10", "Эссенциальная первичная гипертензия", "Essential primary hypertension"),
    _row("I20", "Стенокардия", "Angina pectoris"),
    _row("I21", "Острый инфаркт миокарда", "Acute myocardial infarction"),
    _row("I50", "Сердечная недостаточность", "Heart failure"),
    _row("J06", "Острая инфекция верхних дыхательных путей множественной и неуточнённой локализации", "Acute upper respiratory infections of multiple and unspecified sites"),
    _row("J18", "Пневмония без уточнения возбудителя", "Pneumonia, organism unspecified"),
    _row("J45", "Астма", "Asthma"),
    _row("K35", "Острый аппендицит", "Acute appendicitis"),
    _row("K40", "Паховая грыжа", "Inguinal hernia"),
    _row("K80", "Желчнокаменная болезнь", "Cholelithiasis"),
    _row("K85", "Острый панкреатит", "Acute pancreatitis"),
    _row("L20", "Атопический дерматит", "Atopic dermatitis"),
    _row("M17", "Гонартроз", "Gonarthrosis"),
    _row("M54", "Дорсалгия", "Dorsalgia"),
    _row("N20", "Камни почки и мочеточника", "Calculus of kidney and ureter"),
    _row("N30", "Цистит", "Cystitis"),
    _row("N40", "Гиперплазия предстательной железы", "Hyperplasia of prostate"),
    _row("O80", "Одноплодные самопроизвольные роды", "Single spontaneous delivery"),
    _row("R10", "Боль в животе и тазу", "Abdominal and pelvic pain"),
    _row("R50", "Лихорадка неясного происхождения", "Fever of other and unknown origin"),
    _row("S06", "Внутричерепная травма", "Intracranial injury"),
    _row("S52", "Перелом костей предплечья", "Fracture of forearm"),
    _row("T14", "Травма неуточнённой локализации", "Injury of unspecified body region"),
    _row("Z00", "Общий осмотр и обследование лиц без жалоб или установленного диагноза", "General examination and investigation of persons without complaint or reported diagnosis"),
    _row("Z01", "Другие специальные осмотры и обследования лиц без жалоб или установленного диагноза", "Other special examinations and investigations of persons without complaint or reported diagnosis"),
    _row("Z02", "Осмотр и обращение в административных целях", "Examination and encounter for administrative purposes"),
    _row("Z03", "Медицинское наблюдение и оценка при подозрении на болезнь или патологическое состояние", "Medical observation and evaluation for suspected diseases and conditions"),
    _row("Z34", "Наблюдение за течением нормальной беременности", "Supervision of normal pregnancy"),
    _row("Z51", "Другие виды медицинской помощи", "Other medical care"),
]

_BASE_ROWS: list[tuple[str, str]] = [
    # F00-F09 Organic, including symptomatic, mental disorders
    ("F00", "Деменция при болезни Альцгеймера"),
    ("F00.0", "Деменция при болезни Альцгеймера с ранним началом"),
    ("F00.1", "Деменция при болезни Альцгеймера с поздним началом"),
    ("F00.2", "Деменция при болезни Альцгеймера, атипичная или смешанного типа"),
    ("F00.9", "Деменция при болезни Альцгеймера неуточнённая"),
    ("F01", "Сосудистая деменция"),
    ("F01.0", "Сосудистая деменция с острым началом"),
    ("F01.1", "Мультиинфарктная деменция"),
    ("F01.2", "Подкорковая сосудистая деменция"),
    ("F01.3", "Смешанная корковая и подкорковая сосудистая деменция"),
    ("F01.8", "Другая сосудистая деменция"),
    ("F01.9", "Сосудистая деменция неуточнённая"),
    ("F02", "Деменция при других болезнях, классифицированных в других рубриках"),
    ("F02.0", "Деменция при болезни Пика"),
    ("F02.1", "Деменция при болезни Крейтцфельдта-Якоба"),
    ("F02.2", "Деменция при болезни Гентингтона"),
    ("F02.3", "Деменция при болезни Паркинсона"),
    ("F02.4", "Деменция при болезни, вызванной вирусом иммунодефицита человека"),
    ("F02.8", "Деменция при других уточнённых болезнях"),
    ("F03", "Деменция неуточнённая"),
    ("F04", "Органический амнестический синдром, не вызванный алкоголем или другими психоактивными веществами"),
    ("F05", "Делирий, не вызванный алкоголем или другими психоактивными веществами"),
    ("F05.0", "Делирий, не возникающий на фоне деменции"),
    ("F05.1", "Делирий, возникающий на фоне деменции"),
    ("F05.8", "Другой делирий"),
    ("F05.9", "Делирий неуточнённый"),
    ("F06", "Другие психические расстройства вследствие повреждения и дисфункции головного мозга или соматической болезни"),
    ("F06.0", "Органический галлюциноз"),
    ("F06.1", "Органическое кататоническое расстройство"),
    ("F06.2", "Органическое бредовое расстройство"),
    ("F06.3", "Органические расстройства настроения"),
    ("F06.4", "Органическое тревожное расстройство"),
    ("F06.5", "Органическое диссоциативное расстройство"),
    ("F06.6", "Органическое эмоционально лабильное расстройство"),
    ("F06.7", "Лёгкое когнитивное расстройство"),
    ("F06.8", "Другие уточнённые органические психические расстройства"),
    ("F06.9", "Органическое психическое расстройство неуточнённое"),
    ("F07", "Расстройства личности и поведения вследствие болезни, повреждения или дисфункции головного мозга"),
    ("F07.0", "Органическое расстройство личности"),
    ("F07.1", "Постэнцефалитический синдром"),
    ("F07.2", "Постконтузионный синдром"),
    ("F07.8", "Другие органические расстройства личности и поведения"),
    ("F07.9", "Органическое расстройство личности и поведения неуточнённое"),
    ("F09", "Органическое или симптоматическое психическое расстройство неуточнённое"),

    # F20-F29 Schizophrenia, schizotypal and delusional disorders
    ("F20", "Шизофрения"),
    ("F20.0", "Параноидная шизофрения"),
    ("F20.1", "Гебефреническая шизофрения"),
    ("F20.2", "Кататоническая шизофрения"),
    ("F20.3", "Недифференцированная шизофрения"),
    ("F20.4", "Постшизофреническая депрессия"),
    ("F20.5", "Резидуальная шизофрения"),
    ("F20.6", "Простая шизофрения"),
    ("F20.8", "Другой тип шизофрении"),
    ("F20.9", "Шизофрения неуточнённая"),
    ("F21", "Шизотипическое расстройство"),
    ("F22", "Хронические бредовые расстройства"),
    ("F22.0", "Бредовое расстройство"),
    ("F22.8", "Другие хронические бредовые расстройства"),
    ("F22.9", "Хроническое бредовое расстройство неуточнённое"),
    ("F23", "Острые и преходящие психотические расстройства"),
    ("F23.0", "Острое полиморфное психотическое расстройство без симптомов шизофрении"),
    ("F23.1", "Острое полиморфное психотическое расстройство с симптомами шизофрении"),
    ("F23.2", "Острое шизофреноподобное психотическое расстройство"),
    ("F23.3", "Другие острые преимущественно бредовые психотические расстройства"),
    ("F23.8", "Другие острые и преходящие психотические расстройства"),
    ("F23.9", "Острое и преходящее психотическое расстройство неуточнённое"),
    ("F24", "Индуцированное бредовое расстройство"),
    ("F25", "Шизоаффективные расстройства"),
    ("F25.0", "Шизоаффективное расстройство, маниакальный тип"),
    ("F25.1", "Шизоаффективное расстройство, депрессивный тип"),
    ("F25.2", "Шизоаффективное расстройство, смешанный тип"),
    ("F25.8", "Другие шизоаффективные расстройства"),
    ("F25.9", "Шизоаффективное расстройство неуточнённое"),
    ("F28", "Другие неорганические психотические расстройства"),
    ("F29", "Неорганический психоз неуточнённый"),

    # F30-F39 Mood disorders
    ("F30", "Маниакальный эпизод"),
    ("F30.0", "Гипомания"),
    ("F30.1", "Мания без психотических симптомов"),
    ("F30.2", "Мания с психотическими симптомами"),
    ("F30.8", "Другие маниакальные эпизоды"),
    ("F30.9", "Маниакальный эпизод неуточнённый"),
    ("F31", "Биполярное аффективное расстройство"),
    ("F31.0", "Биполярное аффективное расстройство, текущий эпизод гипомании"),
    ("F31.1", "Биполярное аффективное расстройство, текущий эпизод мании без психотических симптомов"),
    ("F31.2", "Биполярное аффективное расстройство, текущий эпизод мании с психотическими симптомами"),
    ("F31.3", "Биполярное аффективное расстройство, текущий эпизод лёгкой или умеренной депрессии"),
    ("F31.4", "Биполярное аффективное расстройство, текущий эпизод тяжёлой депрессии без психотических симптомов"),
    ("F31.5", "Биполярное аффективное расстройство, текущий эпизод тяжёлой депрессии с психотическими симптомами"),
    ("F31.6", "Биполярное аффективное расстройство, текущий эпизод смешанного характера"),
    ("F31.7", "Биполярное аффективное расстройство, текущая ремиссия"),
    ("F31.8", "Другие биполярные аффективные расстройства"),
    ("F31.9", "Биполярное аффективное расстройство неуточнённое"),
    ("F32", "Депрессивный эпизод"),
    ("F32.0", "Депрессивный эпизод лёгкой степени"),
    ("F32.1", "Депрессивный эпизод средней степени"),
    ("F32.2", "Депрессивный эпизод тяжёлой степени без психотических симптомов"),
    ("F32.3", "Депрессивный эпизод тяжёлой степени с психотическими симптомами"),
    ("F32.8", "Другие депрессивные эпизоды"),
    ("F32.9", "Депрессивный эпизод неуточнённый"),
    ("F33", "Рекуррентное депрессивное расстройство"),
    ("F33.0", "Рекуррентное депрессивное расстройство, текущий эпизод лёгкой степени"),
    ("F33.1", "Рекуррентное депрессивное расстройство, текущий эпизод средней степени"),
    ("F33.2", "Рекуррентное депрессивное расстройство, текущий эпизод тяжёлой степени без психотических симптомов"),
    ("F33.3", "Рекуррентное депрессивное расстройство, текущий эпизод тяжёлой степени с психотическими симптомами"),
    ("F33.4", "Рекуррентное депрессивное расстройство, текущая ремиссия"),
    ("F33.8", "Другие рекуррентные депрессивные расстройства"),
    ("F33.9", "Рекуррентное депрессивное расстройство неуточнённое"),
    ("F34", "Устойчивые расстройства настроения"),
    ("F34.0", "Циклотимия"),
    ("F34.1", "Дистимия"),
    ("F34.8", "Другие устойчивые расстройства настроения"),
    ("F34.9", "Устойчивое расстройство настроения неуточнённое"),
    ("F38", "Другие расстройства настроения"),
    ("F38.0", "Другие одиночные расстройства настроения"),
    ("F38.1", "Другие рекуррентные расстройства настроения"),
    ("F38.8", "Другие уточнённые расстройства настроения"),
    ("F39", "Расстройство настроения неуточнённое"),

    # F40-F48 Neurotic, stress-related and somatoform disorders
    ("F40", "Фобические тревожные расстройства"),
    ("F40.0", "Агорафобия"),
    ("F40.1", "Социальные фобии"),
    ("F40.2", "Специфические изолированные фобии"),
    ("F40.8", "Другие фобические тревожные расстройства"),
    ("F40.9", "Фобическое тревожное расстройство неуточнённое"),
    ("F41", "Другие тревожные расстройства"),
    ("F41.0", "Паническое расстройство"),
    ("F41.1", "Генерализованное тревожное расстройство"),
    ("F41.2", "Смешанное тревожное и депрессивное расстройство"),
    ("F41.3", "Другие смешанные тревожные расстройства"),
    ("F41.8", "Другие уточнённые тревожные расстройства"),
    ("F41.9", "Тревожное расстройство неуточнённое"),
    ("F42", "Обсессивно-компульсивное расстройство"),
    ("F42.0", "Преимущественно навязчивые мысли или размышления"),
    ("F42.1", "Преимущественно компульсивные действия"),
    ("F42.2", "Смешанные навязчивые мысли и действия"),
    ("F42.8", "Другие обсессивно-компульсивные расстройства"),
    ("F42.9", "Обсессивно-компульсивное расстройство неуточнённое"),
    ("F43", "Реакция на тяжёлый стресс и нарушения адаптации"),
    ("F43.0", "Острая реакция на стресс"),
    ("F43.1", "Посттравматическое стрессовое расстройство"),
    ("F43.2", "Расстройства адаптации"),
    ("F43.8", "Другие реакции на тяжёлый стресс"),
    ("F43.9", "Реакция на тяжёлый стресс неуточнённая"),
    ("F44", "Диссоциативные конверсионные расстройства"),
    ("F44.0", "Диссоциативная амнезия"),
    ("F44.1", "Диссоциативная фуга"),
    ("F44.2", "Диссоциативный ступор"),
    ("F44.3", "Транс и одержимость"),
    ("F44.4", "Диссоциативные двигательные расстройства"),
    ("F44.5", "Диссоциативные судороги"),
    ("F44.6", "Диссоциативная анестезия или потеря чувственного восприятия"),
    ("F44.7", "Смешанные диссоциативные конверсионные расстройства"),
    ("F44.8", "Другие диссоциативные конверсионные расстройства"),
    ("F44.9", "Диссоциативное конверсионное расстройство неуточнённое"),
    ("F45", "Соматоформные расстройства"),
    ("F45.0", "Соматизированное расстройство"),
    ("F45.1", "Недифференцированное соматоформное расстройство"),
    ("F45.2", "Ипохондрическое расстройство"),
    ("F45.3", "Соматоформная дисфункция вегетативной нервной системы"),
    ("F45.4", "Устойчивое соматоформное болевое расстройство"),
    ("F45.8", "Другие соматоформные расстройства"),
    ("F45.9", "Соматоформное расстройство неуточнённое"),
    ("F48", "Другие невротические расстройства"),
    ("F48.0", "Неврастения"),
    ("F48.1", "Синдром деперсонализации-дереализации"),
    ("F48.8", "Другие уточнённые невротические расстройства"),
    ("F48.9", "Невротическое расстройство неуточнённое"),

    # F50-F59 Behavioural syndromes associated with physiological disturbances and physical factors
    ("F50", "Расстройства приёма пищи"),
    ("F50.0", "Нервная анорексия"),
    ("F50.1", "Атипичная нервная анорексия"),
    ("F50.2", "Нервная булимия"),
    ("F50.3", "Атипичная нервная булимия"),
    ("F50.4", "Переедание, связанное с другими психологическими расстройствами"),
    ("F50.5", "Рвота, связанная с другими психологическими расстройствами"),
    ("F50.8", "Другие расстройства приёма пищи"),
    ("F50.9", "Расстройство приёма пищи неуточнённое"),
    ("F51", "Расстройства сна неорганической природы"),
    ("F51.0", "Бессонница неорганической природы"),
    ("F51.1", "Сонливость гиперсомния неорганической природы"),
    ("F51.2", "Расстройство режима сна и бодрствования неорганической природы"),
    ("F51.3", "Снохождение сомнамбулизм"),
    ("F51.4", "Ужасы во время сна"),
    ("F51.5", "Кошмары"),
    ("F51.8", "Другие расстройства сна неорганической природы"),
    ("F51.9", "Расстройство сна неорганической природы неуточнённое"),
    ("F52", "Сексуальная дисфункция, не обусловленная органическим расстройством или болезнью"),
    ("F52.0", "Отсутствие или потеря сексуального влечения"),
    ("F52.1", "Отвращение к сексуальной активности и отсутствие сексуального удовольствия"),
    ("F52.2", "Недостаточность генитальной реакции"),
    ("F52.3", "Оргазмическая дисфункция"),
    ("F52.4", "Преждевременная эякуляция"),
    ("F52.5", "Вагинизм неорганической природы"),
    ("F52.6", "Диспареуния неорганической природы"),
    ("F52.7", "Повышенное сексуальное влечение"),
    ("F52.8", "Другие сексуальные дисфункции неорганической природы"),
    ("F52.9", "Сексуальная дисфункция неорганической природы неуточнённая"),
    ("F53", "Психические расстройства и расстройства поведения, связанные с послеродовым периодом"),
    ("F53.0", "Лёгкие психические расстройства и расстройства поведения, связанные с послеродовым периодом"),
    ("F53.1", "Тяжёлые психические расстройства и расстройства поведения, связанные с послеродовым периодом"),
    ("F53.8", "Другие психические расстройства и расстройства поведения, связанные с послеродовым периодом"),
    ("F53.9", "Психическое расстройство, связанное с послеродовым периодом, неуточнённое"),
    ("F54", "Психологические и поведенческие факторы, связанные с болезнями, классифицированными в других рубриках"),
    ("F55", "Злоупотребление веществами, не вызывающими зависимость"),
    ("F59", "Поведенческие синдромы, связанные с физиологическими нарушениями и физическими факторами, неуточнённые"),

    # F60-F69 Disorders of adult personality and behaviour
    ("F60", "Специфические расстройства личности"),
    ("F60.0", "Параноидное расстройство личности"),
    ("F60.1", "Шизоидное расстройство личности"),
    ("F60.2", "Диссоциальное расстройство личности"),
    ("F60.3", "Эмоционально неустойчивое расстройство личности"),
    ("F60.4", "Истерическое расстройство личности"),
    ("F60.5", "Ананкастное расстройство личности"),
    ("F60.6", "Тревожное уклоняющееся расстройство личности"),
    ("F60.7", "Зависимое расстройство личности"),
    ("F60.8", "Другие специфические расстройства личности"),
    ("F60.9", "Расстройство личности неуточнённое"),
    ("F61", "Смешанные и другие расстройства личности"),
    ("F62", "Стойкие изменения личности, не связанные с повреждением или болезнью головного мозга"),
    ("F62.0", "Стойкое изменение личности после переживания катастрофы"),
    ("F62.1", "Стойкое изменение личности после психической болезни"),
    ("F62.8", "Другие стойкие изменения личности"),
    ("F62.9", "Стойкое изменение личности неуточнённое"),
    ("F63", "Расстройства привычек и влечений"),
    ("F63.0", "Патологическое влечение к азартным играм"),
    ("F63.1", "Патологическое влечение к поджогам пиромания"),
    ("F63.2", "Патологическое влечение к воровству клептомания"),
    ("F63.3", "Трихотилломания"),
    ("F63.8", "Другие расстройства привычек и влечений"),
    ("F63.9", "Расстройство привычек и влечений неуточнённое"),
    ("F64", "Расстройства половой идентификации"),
    ("F64.0", "Транссексуализм"),
    ("F64.1", "Трансвестизм двойной роли"),
    ("F64.2", "Расстройство половой идентификации в детском возрасте"),
    ("F64.8", "Другие расстройства половой идентификации"),
    ("F64.9", "Расстройство половой идентификации неуточнённое"),
    ("F65", "Расстройства сексуального предпочтения"),
    ("F65.0", "Фетишизм"),
    ("F65.1", "Фетишистский трансвестизм"),
    ("F65.2", "Эксгибиционизм"),
    ("F65.3", "Вуайеризм"),
    ("F65.4", "Педофилия"),
    ("F65.5", "Садомазохизм"),
    ("F65.6", "Множественные расстройства сексуального предпочтения"),
    ("F65.8", "Другие расстройства сексуального предпочтения"),
    ("F65.9", "Расстройство сексуального предпочтения неуточнённое"),
    ("F66", "Психологические и поведенческие расстройства, связанные с сексуальным развитием и ориентацией"),
    ("F66.0", "Расстройство сексуального созревания"),
    ("F66.1", "Эгодистоническая сексуальная ориентация"),
    ("F66.2", "Расстройство сексуальных отношений"),
    ("F66.8", "Другие психосексуальные расстройства развития"),
    ("F66.9", "Психосексуальное расстройство развития неуточнённое"),
    ("F68", "Другие расстройства личности и поведения в зрелом возрасте"),
    ("F68.0", "Преувеличение физических симптомов по психологическим причинам"),
    ("F68.1", "Преднамеренное вызывание или симуляция симптомов или инвалидности"),
    ("F68.8", "Другие уточнённые расстройства личности и поведения в зрелом возрасте"),
    ("F69", "Расстройство личности и поведения в зрелом возрасте неуточнённое"),

    # F70-F79 Intellectual disability
    ("F70", "Умственная отсталость лёгкой степени"),
    ("F71", "Умственная отсталость умеренная"),
    ("F72", "Умственная отсталость тяжёлая"),
    ("F73", "Умственная отсталость глубокая"),
    ("F78", "Другие формы умственной отсталости"),
    ("F79", "Умственная отсталость неуточнённая"),

    # F80-F89 Disorders of psychological development
    ("F80", "Специфические расстройства развития речи и языка"),
    ("F80.0", "Специфическое расстройство речевой артикуляции"),
    ("F80.1", "Расстройство экспрессивной речи"),
    ("F80.2", "Расстройство рецептивной речи"),
    ("F80.3", "Приобретённая афазия с эпилепсией синдром Ландау-Клеффнера"),
    ("F80.8", "Другие расстройства развития речи и языка"),
    ("F80.9", "Расстройство развития речи и языка неуточнённое"),
    ("F81", "Специфические расстройства развития учебных навыков"),
    ("F81.0", "Специфическое расстройство чтения"),
    ("F81.1", "Специфическое расстройство спеллингования"),
    ("F81.2", "Специфическое расстройство арифметических навыков"),
    ("F81.3", "Смешанное расстройство учебных навыков"),
    ("F81.8", "Другие расстройства развития учебных навыков"),
    ("F81.9", "Расстройство развития учебных навыков неуточнённое"),
    ("F82", "Специфическое расстройство развития моторной функции"),
    ("F83", "Смешанные специфические расстройства психологического развития"),
    ("F84", "Общие расстройства психологического развития"),
    ("F84.0", "Детский аутизм"),
    ("F84.1", "Атипичный аутизм"),
    ("F84.2", "Синдром Ретта"),
    ("F84.3", "Другое дезинтегративное расстройство детского возраста"),
    ("F84.4", "Гиперактивное расстройство, сочетающееся с умственной отсталостью и стереотипными движениями"),
    ("F84.5", "Синдром Аспергера"),
    ("F84.8", "Другие общие расстройства психологического развития"),
    ("F84.9", "Общее расстройство психологического развития неуточнённое"),
    ("F88", "Другие расстройства психологического развития"),
    ("F89", "Расстройство психологического развития неуточнённое"),

    # F90-F98 Behavioural and emotional disorders with onset usually occurring in childhood/adolescence
    ("F90", "Гиперкинетические расстройства"),
    ("F90.0", "Нарушение активности и внимания"),
    ("F90.1", "Гиперкинетическое расстройство поведения"),
    ("F90.8", "Другие гиперкинетические расстройства"),
    ("F90.9", "Гиперкинетическое расстройство неуточнённое"),
    ("F91", "Расстройства поведения"),
    ("F91.0", "Расстройство поведения, ограниченное рамками семьи"),
    ("F91.1", "Несоциализированное расстройство поведения"),
    ("F91.2", "Социализированное расстройство поведения"),
    ("F91.3", "Оппозиционно-вызывающее расстройство"),
    ("F91.8", "Другие расстройства поведения"),
    ("F91.9", "Расстройство поведения неуточнённое"),
    ("F92", "Смешанные расстройства поведения и эмоций"),
    ("F92.0", "Депрессивное расстройство поведения"),
    ("F92.8", "Другие смешанные расстройства поведения и эмоций"),
    ("F92.9", "Смешанное расстройство поведения и эмоций неуточнённое"),
    ("F93", "Эмоциональные расстройства, начало которых специфично для детского возраста"),
    ("F93.0", "Тревожное расстройство у детей, вызванное разлукой"),
    ("F93.1", "Фобическое тревожное расстройство детского возраста"),
    ("F93.2", "Социальное тревожное расстройство детского возраста"),
    ("F93.3", "Расстройство сиблингового соперничества"),
    ("F93.8", "Другие эмоциональные расстройства детского возраста"),
    ("F93.9", "Эмоциональное расстройство детского возраста неуточнённое"),
    ("F94", "Расстройства социального функционирования, начало которых характерно для детского и подросткового возраста"),
    ("F94.0", "Элективный мутизм"),
    ("F94.1", "Реактивное расстройство привязанности детского возраста"),
    ("F94.2", "Расторможенное расстройство привязанности детского возраста"),
    ("F94.8", "Другие расстройства социального функционирования детского возраста"),
    ("F94.9", "Расстройство социального функционирования детского возраста неуточнённое"),
    ("F95", "Тики"),
    ("F95.0", "Транзиторные тики"),
    ("F95.1", "Хронические моторные или вокальные тики"),
    ("F95.2", "Комбинированные вокальные и множественные моторные тики синдром Туретта"),
    ("F95.8", "Другие тики"),
    ("F95.9", "Тик неуточнённый"),
    ("F98", "Другие эмоциональные расстройства и расстройства поведения, начинающиеся обычно в детском и подростковом возрасте"),
    ("F98.0", "Энурез неорганической природы"),
    ("F98.1", "Энкопрез неорганической природы"),
    ("F98.2", "Расстройство приёма пищи в младенческом и детском возрасте"),
    ("F98.3", "Поедание несъедобного младенцами и детьми"),
    ("F98.4", "Стереотипные двигательные расстройства"),
    ("F98.5", "Заикание"),
    ("F98.6", "Речь взахлёб"),
    ("F98.8", "Другие уточнённые эмоциональные расстройства и расстройства поведения"),
    ("F98.9", "Эмоциональное расстройство и расстройство поведения неуточнённое"),
    ("F99", "Психическое расстройство без дополнительных уточнений"),
]


_SUBSTANCE_TITLES = {
    "F10": "алкоголя",
    "F11": "опиоидов",
    "F12": "каннабиноидов",
    "F13": "седативных или снотворных средств",
    "F14": "кокаина",
    "F15": "других стимуляторов, включая кофеин",
    "F16": "галлюциногенов",
    "F17": "табака",
    "F18": "летучих растворителей",
    "F19": "нескольких наркотических средств и других психоактивных веществ",
}

_SUBSTANCE_STATES = {
    "0": "острая интоксикация",
    "1": "пагубное употребление",
    "2": "синдром зависимости",
    "3": "состояние отмены",
    "4": "состояние отмены с делирием",
    "5": "психотическое расстройство",
    "6": "амнестический синдром",
    "7": "резидуальное психотическое расстройство или психотическое расстройство с поздним дебютом",
    "8": "другие психические и поведенческие расстройства",
    "9": "психическое и поведенческое расстройство неуточнённое",
}


def _substance_rows() -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for code, substance in _SUBSTANCE_TITLES.items():
        rows.append((code, f"Психические и поведенческие расстройства вследствие употребления {substance}"))
        for suffix, state in _SUBSTANCE_STATES.items():
            rows.append((f"{code}.{suffix}", f"Расстройство вследствие употребления {substance}: {state}"))
    return rows


def _build_rows() -> list[ICD10Diagnosis]:
    combined: list[ICD10Diagnosis] = (
        list(_SECTION_ROWS)
        + list(_BLOCK_ROWS)
        + list(_COMMON_RUBRIC_ROWS)
        + [_row(code, title) for code, title in _BASE_ROWS]
    )
    insert_at = len(combined)
    for idx, item in enumerate(combined):
        if item.code == "F20":
            insert_at = idx
            break
    combined[insert_at:insert_at] = [_row(code, title) for code, title in _substance_rows()]

    seen: set[str] = set()
    diagnoses: list[ICD10Diagnosis] = []
    for item in combined:
        if item.code in seen:
            continue
        seen.add(item.code)
        diagnoses.append(item)
    return sorted(diagnoses, key=lambda d: _code_sort_key(d.code))


def _code_sort_key(code: str) -> tuple[int, ...]:
    text = str(code or "").upper()
    letters = re.findall(r"[A-ZА-Я]", text)
    letter_index = ord(letters[0]) - ord("A") + 1 if letters and "A" <= letters[0] <= "Z" else 0
    digits = [int(item) for item in re.findall(r"\d+", text)]
    return (letter_index, *digits)


def _language_complete(item: ICD10Diagnosis) -> bool:
    return all(item.title_for_language(lang) for lang in _LANGS)


def assert_icd10_full_catalog_lock() -> None:
    expected_sections = {
        "A00-B99", "C00-D48", "D50-D89", "E00-E90", "F00-F99", "G00-G99",
        "H00-H59", "H60-H95", "I00-I99", "J00-J99", "K00-K93", "L00-L99",
        "M00-M99", "N00-N99", "O00-O99", "P00-P96", "Q00-Q99", "R00-R99",
        "S00-T98", "V01-Y98", "Z00-Z99", "U00-U99",
    }
    codes = {item.code for item in ICD10_DIAGNOSES}
    missing = sorted(expected_sections - codes)
    if missing:
        raise AssertionError("ICD-10 full chapter catalog is incomplete: " + ", ".join(missing))
    if not any(item.code.startswith("F") for item in ICD10_DIAGNOSES):
        raise AssertionError("ICD-10 catalog lost F-class rows")
    if not any(item.code.startswith("K") for item in ICD10_DIAGNOSES):
        raise AssertionError("ICD-10 catalog is still F-class-only: K-class missing")
    section_rows = [item for item in ICD10_DIAGNOSES if item.kind == _SECTION_KIND]
    for lang in _LANGS:
        if not all(item.title_for_language(lang) for item in section_rows):
            raise AssertionError(f"ICD-10 section title missing for language: {lang}")


ICD10_DIAGNOSES: list[ICD10Diagnosis] = _build_rows()
# Backward-compatible alias: old code imports ICD10_F_DIAGNOSES.
ICD10_F_DIAGNOSES: list[ICD10Diagnosis] = ICD10_DIAGNOSES
